# Generated by Django 3.1.4 on 2020-12-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='../mediafiles/user.png', null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
