# Generated by Django 3.1.4 on 2020-12-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='./mediafiles/user.png', null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
