# Generated by Django 3.1.4 on 2020-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201221_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/user.png', null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
