# Generated by Django 3.1.6 on 2021-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210216_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='44757', max_length=30),
        ),
    ]
