# Generated by Django 3.1.4 on 2020-12-23 03:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201221_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='played_recordings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='recently_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None),
        ),
    ]
