# Generated by Django 3.1.6 on 2021-02-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210216_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='342333', max_length=30),
        ),
    ]
