# Generated by Django 3.1.4 on 2020-12-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201223_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='played_recordings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recently_played',
        ),
    ]
