# Generated by Django 3.1.6 on 2021-03-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210301_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='229419', max_length=30),
        ),
    ]
