# Generated by Django 3.1.6 on 2021-04-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210309_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True), max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True), max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='018916', max_length=30),
        ),
    ]
