# Generated by Django 3.1.4 on 2020-12-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0002_auto_20201221_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='audios',
        ),
        migrations.AddField(
            model_name='playlist',
            name='audios',
            field=models.ManyToManyField(to='memoryze.Audio'),
        ),
    ]
