# Generated by Django 3.1.4 on 2020-12-21 03:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0003_auto_20201221_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='audios',
        ),
        migrations.AddField(
            model_name='playlist',
            name='audios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=[], size=None),
        ),
    ]
