# Generated by Django 3.1.4 on 2020-12-21 03:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0004_auto_20201221_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='audios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None),
        ),
    ]
