# Generated by Django 3.1.4 on 2021-01-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0004_auto_20210101_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
