# Generated by Django 3.1.4 on 2020-12-21 04:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0005_auto_20201221_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=['general'], size=None),
        ),
    ]
