# Generated by Django 3.1.6 on 2021-02-22 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0005_auto_20210101_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='audios',
        ),
        migrations.AddField(
            model_name='audio',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audios', related_query_name='audio', to='memoryze.playlist'),
        ),
    ]
