# Generated by Django 3.1.6 on 2021-02-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0006_auto_20210222_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='descriptive_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
