# Generated by Django 3.1.4 on 2020-12-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0007_auto_20201221_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, default='../mediafiles/audio.png', null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
