# Generated by Django 3.1.4 on 2020-12-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0008_audio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, default='./mediafiles/audio.png', null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
