# Generated by Django 3.1.4 on 2020-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryze', '0010_auto_20201221_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, default='media/audio.png', null=True, upload_to='images/%Y/%m/%D/'),
        ),
    ]
