# Generated by Django 3.1.4 on 2020-12-23 08:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memoryze', '0012_auto_20201221_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_recordings', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None)),
                ('recently_played', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', related_query_name='tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
